apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: freeswitch-configs
  name: freeswitch-configs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
