apiVersion: v1
kind: PersistentVolume
metadata:
  name: freeswitch-configs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: '/etc/freeswitch'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: freeswitch-configs
  name: freeswitch-configs
spec:
  storageClassName: manual
  volumeName: freeswitch-configs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
